### ISSUE TITLE
Handling of parsed PE Header for writer

### ISSUE THREAD

**Issue by GanbaruTobi** [RaitoBezarius/ifrit#1]
I tried to write a parsed PE to file.

```rust
let mut pe_mem = goblin::pe::PE::parse_with_opts(memory_data, &poptions)?; 
for section in &mut pe_mem.sections {
        section.pointer_to_raw_data = section.virtual_address;
        section.size_of_raw_data = section.virtual_size;
}
let mut pe_writer = PEWriter::new(pe_mem).expect("Failed to create a wrapper");
let new_pe = pe_writer.write_into().unwrap();
std::fs::write(name.to_string(), &new_pe[..]).unwrap();
```
The writer modifies the PE without my interaction. Sadly only my set virtual_address is accepted. The size is being reset to the original values.

The following screenshot shows the .reloc section three times.
1) original section
2) then modified with the code above
3) the result if I read the file that pe_writer wrote back in:
![grafik](https://github.com/RaitoBezarius/ifrit/assets/15239745/118157e2-a8c4-41f2-bdf3-a3db2e6f6eb8)

I see two options here, either the pe_writer respects the &pe_mem reference and doesn't modify it on its own or ifrit should clearly state that all modifications have to happen trough the pe_writer and make all pe fields accessible.

**Comment by RaitoBezarius** [comment]
Maybe it's not clear enough from docs / etc. (open to suggestions on that)

But the library is not made for you changing arbitrary elements and expecting the layoutting to work out of the box.
It's made to recompute the offsets that cannot be predicted, e.g. the pointer on disk.

If you want to write a structure as-is, serialize it, this is not this library's concern per se, but just normal Goblin usage.

**Comment by GanbaruTobi** [comment]
Oh, okey, i was brought here from goblin ( https://github.com/m4b/goblin/issues/394) so might have been an confusion.
