### ISSUE TITLE
Does it support Functions out of the box?

### ISSUE THREAD

**Issue by Cr0a3** [RaitoBezarius/ifrit#2]
Hi, cool project. I wanted to ask if it supports adding functions symbols function import, etc... (like faerie). 
I sadly can't use farie because it doesn't supports PE-Coff.

**Comment by Cr0a3** [comment]
@RaitoBezarius

**Comment by RaitoBezarius** [comment]
No, it's very barebone and is not intended yet to be used to make a compiler, for example. You'd need to carve your own way on the top of that code to make those features available.

**Comment by Cr0a3** [comment]
Ok, thanks
