### ISSUE TITLE
Get in contact

### ISSUE THREAD

**Issue by qknight** [RaitoBezarius/ifrit#3]
I find your project quite interesting for my libnix project to rewrite PE headers and the .idata section. Maybe you can guide me a little with that? If so, please contact me at js@lastlog.de and since libnix is a NLnet sponsored project I can offer you some money for your help in return.

Btw: I did not find any contact details on your profiles so I try this issue instead, sorry for that.

Regards,
qknight

**Comment by RaitoBezarius** [comment]
@qknight Hi there, let's get in touch over Matrix or IRC or whatever, I am involved in the NixOS community, so… :)

**Comment by qknight** [comment]
Didn't find you there, that is why I was asking in the first place. Thanks anyways.

**Comment by qknight** [comment]
I guess that `ifrit` modifying PE is similar to this tool https://github.com/CnCNet/petool which also stated that extending the PE header might work and sometimes might fail. So this is pretty hard it seems.
